### ISSUE TITLE
how to properly use external library, and why blure and focus been triggered twice for once click 

### ISSUE THREAD

**Issue by ShuangmingLiu** [Geotab/generator-addin#12]
Hello, i have a hard time for use the external libraries for new addin project, i can see my libraries under source folder, but i don't know how to access it.  Would you mind show me an example about how to use any .js file with main.js together? 

i loaded external sources in index.js by require(../libraries/....) and followed the instruction to put my libraries file under src folder but outside the app folder, can not make it ready to use on my add in. 
thanks ahead, and have a good one!

**Comment by beefo** [comment]
Here's one way, I'm sure there are many.

1. Use npm to install external libraries. 
`npm install vue --save`

2. Add this to the `eslintConfig` section of project.json file:
```
"parserOptions": {
  "sourceType": "module"
}
```

3. Import the library in the main.js file.
`import Vue from 'vue/dist/vue';`

4. Use the library in main.js.
`let widget = new Vue({"el": "#myaddin"})`

**Comment by ShuangmingLiu** [comment]
Hi Beefo, 
thanks for your answer, actually i know the "import" solution which you just list above, but i really want to understand why the "require" option packed everything properly but not working, this may have some potential problem for our project, therefore better for me to understand the reason then i can explain to everyone else in our company, again thanks a lot for explanation.

**Comment by beefo** [comment]
Can you provide an example of what is not working for you and step by step how to reproduce?
